# Generated by Django 3.1 on 2020-09-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Date last updated')),
                ('message_start', models.TimeField(verbose_name='Repeat message start time')),
                ('message_end', models.TimeField(blank=True, verbose_name='Repeat message stop time')),
                ('message_duration', models.DurationField(blank=True, verbose_name='Repeat message duration')),
                ('frequency', models.DurationField(verbose_name='Repeat message every')),
                ('active', models.BooleanField(default=True, verbose_name='Active message')),
            ],
        ),
    ]
