# Generated by Django 3.1 on 2020-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Repeat message duration'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Repeat message stop time'),
        ),
    ]
