# Generated by Django 3.1 on 2020-09-17 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0002_auto_20200916_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Day to end playing message'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Day to start playing message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='frequency',
            field=models.DurationField(verbose_name='Repeat message every (hh:mm:ss)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Repeat message duration (hh:mm:ss)'),
        ),
    ]
