# Generated by Django 3.1 on 2020-09-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0003_auto_20200917_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_duration',
        ),
    ]
